//Prueba 1: Ver si el servidor responde en general
GET http://localhost:3000/test-api

### -----LIBRO----- ###

//Insertar el libro
POST http://localhost:3000/libros
Content-Type: application/json

{
  "id": 1,
  "Nombre": "El Resplandor",
  "Genero": 1,
  "Autor": "Stephen King",
  "fecha_recepcion": "2026-06-06",
  "cantidad_copias": 5,
  "edad_sugerida": 18,
  "editorial": "Debolsillo",
  "precio": 15000,
  "estado": true
}

###

###Listar todos los Libros Disponibles con Stock (Punto 11 del Taller)
GET http://localhost:3000/libros/disponibles


### -----TRABAJADOR----- ###

//No funciona
//Probar Registro de Trabajador
POST http://localhost:3000/trabajador/registro
Content-Type: application/json

{
  "rut": "12345678-9",
  "nombre": "Diego Pérez",
  "correo": "diego@ucn.cl",
  "contrasena": "clave123",
  "bono": 50000
}